### ISSUE TITLE
Uma ideia!!

### ISSUE THREAD

**Issue by Amanda-Foxx** [pjandl/opy1#3]
Se conseguiu: Todos estão acessíveis é bem fáceis de compreender o passo a passo
O que foi fácil: em geral as imagens facilitaram bastante o entendimento de como cada tipo funciona
O que não foi: os notbooks que tiveram o "Format" me causo um pouco de estranheza e cheguei a pensar que fosse um erro os "{:d}" neste caso, eu imagino que seja legal ter um comentário de como ele funciona uma linha antes porque mesmo que explique em aula quem não comparecer pode acreditar ser um erro ou não entender.
Do que sentiu falta: neste Notbook 2 acho que esta bem completo e que todos os alunos com os exemplos consigam realizar a lista de exercícios.

**Comment by pjandl** [comment]
Realmente, o uso da função format para Strings, além dos marcadores utilizados, estava meio jogado.
Comentários e exemplos complementares adicionados em 
OP1-07-Aplicacoes-Repeticao-Condicional.ipynb
que é o primeiro notebook que faz uso disso.
