### ISSUE TITLE
Compartilhando conteúdo usado na antiga oficina de python

### ISSUE THREAD

**Issue by lucaspagliari** [pjandl/opy1#5]
Boa tarde professor!  
Durante minha graduação ministrei uma oficina de python com meus colegas de sala. Caso queira reaproveitar algum conteúdo, ou até mesmo os notebooks que fizemos, link é este:  
[Link do repositório](https://github.com/pytec-jundiai/oficina2019-1)

**Comment by pjandl** [comment]
Bom dia Lucas!

Tudo bom com você?
Puxa, agradeço sua gentileza!
Vou olhar seus materiais sim!
Um abraço 

Peter Jandl Jr
